site_name: NAVIX
site_author: Eduardo Pignatelli
site_description: A reimplementation of MiniGrid in JAX
site_url: https://epignatelli/navix

# GitHub
repo_name: epignatelli/navix
repo_url: https://github.com/epignatelli/navix
use_directory_urls: false
# mkdocstrings
watch:
  - navix

nav:
  - Home:
      - Welcome: index.md
      - Environments: home/environments.md
  - Quickstart:
      - "Getting started": examples/getting_started.ipynb
      - "PPO": examples/ppo.ipynb
      - "Customizing envs": examples/customisation.ipynb
  - Install: install/index.md
  - Becnhmarks: benchmarks/index.md
  - API: api/
  - Changelog: https://github.com/epignatelli/navix/releases

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/epignatelli/navix
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/navix/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/edupignatelli
    - icon: fontawesome/brands/google-scholar
      link: https://github.com/epignatelli/navix

extra_css:
  - assets/stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js

theme:
  name: "material"
  logo: assets/images/navix_logo.png
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.instant
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  palette:
    - scheme: default
      primary: pink
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: light green
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_bases: true
            show_source: false
            heading_level: 3
            show_root_full_path: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_signature: true
            show_signature_annotations: false
            signature_crossrefs: false
  - search
  - gen-files:
      scripts:
        - docs/scripts/gen_doc_stubs.py # or any other name or path
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

markdown_extensions:
  - toc:
      toc_depth: 5
  - pymdownx.highlight
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details # For collapsible admonitions
  - pymdownx.superfences

copyright: Copyright &copy; 2023 - 2024 NAVIX Authors
